# Base year residential demand for TIMES-NZ 3.0.

WorkBookName = "VT_TIMESNZ_RES"

###########################################
# BaseYear Demand 
###########################################


[ResidentialEndUseCommodityDefinitions]
Description = "Defines enduse residential commodities, such as space heating"
SheetName = "Residential demand"
TagName = "FI_Comm"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_res/enduse_commodity_definitions.csv"

[ResidentialFuelCommodityDefinitions]
Description = "Defines residential input fuel commodities, such as electricity (RESELC)"
SheetName = "Residential demand"
TagName = "FI_Comm"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_res/fuel_commodity_definitions.csv"

[ResidentialProcessDefinitions]
Description = "Defines residential enduse processes, such as heatpumps"
SheetName = "Residential demand"
TagName = "FI_Process"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_res/demand_process_definitions.csv"

[ResidentialDemand]
Description = "Residential base year demand topology and technical parameters"
SheetName = "Residential demand"
TagName = "FI_T"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_res/residential_baseyear_demand.csv"

[ResidentialDemand2]
Description = "Summary of residential base year demand topology and technical parameters by commodity"
SheetName = "Residential demand"
TagName = "FI_T: Demand"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_res/residential_baseyear_demand2.csv"

###############################################################################
# Fuel Delivery
###############################################################################

[ResidentialFuelProcessDefinitions]
Description = "Defines residential fuel delivery processes that convert fuels (like NGA) into RES fuels (INDNGA)"
SheetName = "Fuel Delivery"
TagName = "FI_Process"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_res/fuel_delivery_definitions.csv"

[ResidentialFuelProcessParameters]
Description = "Sets parameters for residential fuel delivery processes (mostly delivery costs)"
SheetName = "Fuel Delivery"
TagName = "FI_T"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_res/fuel_delivery_parameters.csv"


###############################################################################
# Emissions
###############################################################################


[ResidentialEmissionsDefinitions]
Description = "Defines the residential emissions commodity"
SheetName = "Emissions"
TagName = "FI_Comm"
Csets =    ["ENV"]
CommName = ["RESCO2"]
Unit =     ["kt"]
CTSLvl =   ["ANNUAL"]

[ResidentialEmissionsParameters]
Description = "Defines emissions factors for residential fuels. Currently hardcoded and need a proper update. To do with all other demand emission factors for consistency"
SheetName = "Emissions"
TagName = "COMEMI"
CommName = "RESCO2"
RESCOA = 92
RESNGA = 53.96
RESLPG = 60.43
RESDSL = 69.69
RESWOD = 4 # rough estimate - need to update with better residential wood calorific value assumptions!


