# Base year transport sector settings for TIMES-NZ

WorkBookName = "VT_TIMESNZ_TRATECH"

###############################################################################
# All SCENARIO
###############################################################################

[TransportNewTechProcessDefinitions]
Description = "Defines processes for future transport technologies"
SheetName = "TRA_NEW"
TagName = "FI_Process"
DataLocation = "data_intermediate/stage_4_veda_format/future_year_tra/tra_newtech_process_definitions.csv"

[TransportNewTechParameters]
Description = "Defines technical parameters for future transport technologies"
SheetName = "TRA_NEW"
TagName = "FI_T"
DataLocation = "data_intermediate/stage_4_veda_format/future_year_tra/newtech_process_parameters.csv"