# Base year transport sector settings for TIMES-NZ

WorkBookName = "VT_TIMESNZ_NewTransport"

###############################################################################
# KEA 
###############################################################################

[TransportNewTechKeaParameters]
Description = "Defines technical parameters for future transport technologies"
SheetName = "TRA_NEW_KEA"
TagName = "FI_T"
DataLocation = ""
Columns = ["TechName","Comm-IN","Comm-OUT","START","EFF","EFF~2030","EFF~2050","CEFF","CEFF~2030","CEFF~2050","AFA","AFA~2050","Life","INVCOST","INVCOST~2030","INVCOST~2040","INVCOST~2050","INVCOST~0","FIXOM","CAP2ACT","Share"]

[TransportNewTechKeaProcessDefinitions]
Description = "Defines processes for future transport technologies"
SheetName = "TRA_NEW_KEA"
TagName = "FI_Process"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_tra/tra_newtech_process_definitions.csv"

###############################################################################
# TUI
###############################################################################

[TransportNewTechTuiParameters]
Description = "Defines technical parameters for future transport technologies"
SheetName = "TRA_NEW_TUI"
TagName = "FI_T"
DataLocation = ""
Columns = ["TechName","Comm-IN","Comm-OUT","START","EFF","EFF~2030","EFF~2050","CEFF","CEFF~2030","CEFF~2050","AFA","AFA~2050","Life","INVCOST","INVCOST~2030","INVCOST~2040","INVCOST~2050","INVCOST~0","FIXOM","CAP2ACT","Share"]

[TransportNewTechTuiProcessDefinitions]
Description = "Defines processes for future transport technologies"
SheetName = "TRA_NEW_TUI"
TagName = "FI_Process"
DataLocation = "data_intermediate/stage_4_veda_format/base_year_tra/tra_newtech_process_definitions.csv"