# New commercial sector technologies for TIMES-NZ

WorkBookName = "SubRES_TMPL/SubRES_NewTechs_COM"

###############################################################################
# Same for both scenarios
###############################################################################

[CommercialNewTechProcessDefinitions]
Description = "Defines processes for future commercial technologies"
SheetName = "COM_NEW"
TagName = "FI_Process"
DataLocation = "data_intermediate/stage_4_veda_format/subres_com/future_commercial_processes.csv"

[CommercialNewTechParameters]
Description = "Defines technical parameters for future commercial technologies"
SheetName = "COM_NEW"
TagName = "FI_T"
DataLocation = "data_intermediate/stage_4_veda_format/subres_com/future_commercial_parameters.csv"
