# Base year transport sector technologies for TIMES-NZ

WorkBookName = "SubRES_TMPL/SubRES_NewTechs_TRA_Standard"

###############################################################################
# Standard scenario 
###############################################################################

[TransportNewTechProcessDefinitions]
Description = "Defines processes for future transport technologies, using standard cost curves"
SheetName = "TRA_NEW"
TagName = "FI_Process"
DataLocation = "data_intermediate/stage_4_veda_format/subres_tra/future_transport_processes.csv"

[TransportNewTechParameters]
Description = "Defines technical parameters for future transport technologies"
SheetName = "TRA_NEW"
TagName = "FI_T"
DataLocation = "data_intermediate/stage_4_veda_format/subres_tra/future_transport_details_standard_costcurve.csv"


###############################################################################
# Advanced scenario
# This is the same, but uses faster declining cost curves for the new processes 
# used for the TIMES-NZ 3.0 Transformation scenario
# Goes into a separate subres file, uses same process definition file 
# So note new WorkBookName used for these 
###############################################################################

[TransportNewTechProcessDefinitionsAdvanced]
Description = "Defines processes for future transport technologies"
WorkBookName = "SubRES_TMPL/SubRES_NewTechs_TRA_Advanced"
SheetName = "TRA_NEW"
TagName = "FI_Process"
DataLocation = "data_intermediate/stage_4_veda_format/subres_tra/future_transport_processes.csv"

[TransportNewTechParametersAdvanced]
Description = "Defines technical parameters for future transport technologies, using advanced cost curves"
WorkBookName = "SubRES_TMPL/SubRES_NewTechs_TRA_Advanced"
SheetName = "TRA_NEW"
TagName = "FI_T"
DataLocation = "data_intermediate/stage_4_veda_format/subres_tra/future_transport_details_advanced_costcurve.csv"
